CREATE TYPE id_text AS TABLE (
   id INT,
   TEXT NVARCHAR(20)
   );

CREATE COLUMN TABLE farben (farbe NVARCHAR(20));

CREATE COLUMN TABLE groessen (groesse VARCHAR(5));

CREATE COLUMN TABLE benutzer (
   id INT PRIMARY KEY,
   vorname NVARCHAR(20),
   nachname NVARCHAR(20),
   email NVARCHAR(50),
   geschlecht VARCHAR(1),
   team INT
   );

CREATE COLUMN TABLE team_text (
   id INT,
   sprache VARCHAR(2),
   team_text NVARCHAR(20),
   PRIMARY KEY (
      id,
      sprache
      )
   );

CREATE COLUMN TABLE projekte (
   id INT PRIMARY KEY,
   titel NVARCHAR(40),
   projektleiter INT,
   aufwandsschaetzung INT,
   anfangsdatum DATE,
   STATUS INT
   );

CREATE COLUMN TABLE aufgaben (
   id INT PRIMARY KEY,
   projekt INT,
   titel NVARCHAR(40),
   beschreibung CLOB,
   STATUS INT,
   bearbeiter INT,
   plan_aufwand INT,
   ist_aufwand INT,
   anlagedatum DATE,
   faelligkeit DATE,
   fertigstellung INT
   );

CREATE TABLE STATUS (
   id INT PRIMARY KEY,
   is_final boolean,
   is_open boolean
   );

CREATE COLUMN TABLE status_Text (
   id INT,
   sprache VARCHAR(2),
   status_text NVARCHAR(20),
   PRIMARY KEY (
      id,
      sprache
      )
   );

CREATE COLUMN TABLE aufgaben_log (
   aufgabe INT,
   zeitstempel TIMESTAMP,
   STATUS INT,
   benutzer INT,
   PRIMARY KEY (
      aufgabe,
      zeitstempel
      )
   );

CREATE COLUMN TABLE bw_daten (
   id INT PRIMARY KEY,
   calday VARCHAR(8)
   );

CREATE COLUMN TABLE error_log (
   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   zeitstempel TIMESTAMP,
   fehlercode INT,
   nachricht NVARCHAR(500)
   );
